name = "secret-santa-box-picker"
main = "dist/worker.js"
compatibility_date = "2024-12-01"

[durable_objects]
bindings = [
  { name = "SECRET_SANTA_ROOM", class_name = "SecretSantaRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["SecretSantaRoom"]
